### PR TITLE
Schools Create and Index Page and Fixed Backend Issues

### LINKED ISSUE #29: School Index Page
Part of Epic #4

### LINKED ISSUE #30: School Create Page
Part of Epic #4

### PR DESCRIPTION
**Pull request by SR33G33**
Closes #30 
Closes #29 

Implemented the path for Admin to go to school management page. The NavBar takes the admin to the schools index page

image

Create School button leads to the create page for schools which works and successfully adds the school to the index page and the db

image

Back to index page

image

All course staff and group members should have admin access

dev deployment at this link: https://proj-organic-sr33g33-dev.dokku-12.cs.ucsb.edu/

In the backend, I changed the schoolController to take in a school json object instead of @getParams because of an issue I was facing in testing where the received input was undefined

### CODE REVIEW

**Review by jason-rodrigues — COMMENTED** [review]
I think you may have mixed up the description and regex checkers.
Could someone else confirm/deny this?

**Comment by SR33G33** [comment]
I believe the term description needs to follow the regex you inputted, so for your inputted regex the term description would simply be S24, F23 

image

Like so

**Review by jason-rodrigues — DISMISSED** [review]
LGTM

**Comment by sanilkatula** [comment]
Screenshot 2024-05-30 at 5 29 01 PM


This should not be happening.

Term Regex and Term Description cant be this. 

so the problem is when you are actually creating the school everything works fine and regex is checked properly but when you update the school its not checking for regex properly. Maybe try adding regex checks on the edit page as well.

**Review by sanilkatula — CHANGES_REQUESTED** [review]
check CR

**Comment by SR33G33** [comment]
I added this as a bug which I pointed out in my edit page PR, I added it as a new task on the kanban board and am fixing it in a separate PR, I believe that the index and create pages are correct

**Comment by pconrad** [comment]
The create school button leads to an error message for me on the dokku deployment linked in the PR.

I can't merge this unless/until I can test it.

**Comment by SR33G33** [comment]
redeployed on dokku seems to be working on my end

**Review by pconrad — CHANGES_REQUESTED** [review]
You cannot delete .env.SAMPLE.  It is an essential file for the app.

Also: is it the intention in this PR to have the index page and create feature for school but to have edit and delete both return errors?

That's typically not mergeable.  We ask that the button at least link to a placeholder page, or put up a message sayig "not yet implemented".

I might relent in this case, but it's bad practice.  So I need clarity on that.

**Comment by SR33G33** [comment]
I accidentally deleted the .env.SAMPLE file, I restored it from the version that is on the main branch

The dokku deployment now has the branch version that has the real functionality for edit and delete instead of errors. 

I should have inserted placeholder pages however I originally intended to have implemented all 3 functionalities in the same PR but later decided to break up the PR's for organizations sake so I just never got around to putting in placeholders as I just did them one after another.

File: src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java [hunk 1]
```diff
@@ -112,34 +111,21 @@ public Object deleteSchool(
...
 
-        if (!abbrev.equals(abbrev.toLowerCase())){
+        if (!school.getAbbrev().equals(school.getAbbrev().toLowerCase())){
             throw new IllegalArgumentException("Invalid abbrev format. Abbrev must be all lowercase");
         }
 
+        if (!school.getTermDescription().matches(school.getTermRegex())) {
+            throw new IllegalArgumentException("Invalid termDescription format. It must follow the pattern " + school.getTermRegex());
+        }
+
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java]: As long as we are editing this file, let's fix this, because this was never the intention of this field.

The term description is just supposed to be the word "Quarter" (e.g. for UCSB) or "Semester" (e.g. for Washington State).

Just remove this.

```suggestion
```

File: frontend/src/tests/pages/SchoolCreatePage.test.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+        const termRegexField = screen.getByTestId("SchoolForm-termRegex");
+        const termDescriptionField = screen.getByTestId("SchoolForm-termDescription");
+        const termErrorField = screen.getByTestId("SchoolForm-termError");
+        const submitButton = screen.getByTestId("SchoolForm-submit");
+
+
+        fireEvent.change(abbrevField, { target: { value: 'ucsb' } });
+        fireEvent.change(nameField, { target: { value: 'UC Santa Barbara' } });
+        fireEvent.change(termRegexField, { target: { value: '[WSMF]\\d\\d' } });
+        fireEvent.change(termDescriptionField, { target: { value: 's24' } });
```
Comment (pconrad) [inline frontend/src/tests/pages/SchoolCreatePage.test.js]:
```suggestion
        fireEvent.change(termDescriptionField, { target: { value: 'quarter' } });
```

File: frontend/src/tests/pages/SchoolCreatePage.test.js [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+        fireEvent.click(submitButton);
+
+        await waitFor(() => expect(axiosMock.history.post.length).toBe(1));
+
+        expect(axiosMock.history.post[0].data).toEqual(
+            JSON.stringify({
+                "abbrev": "ucsb",
+                "name": "UC Santa Barbara",
+                "termRegex": "[WSMF]\\d\\d",
+                "termDescription": "s24",
```
Comment (pconrad) [inline frontend/src/tests/pages/SchoolCreatePage.test.js]:
```suggestion
                "termDescription": "quarter",
```

**Review by pconrad — CHANGES_REQUESTED** [review]
Looks much better! There is still one issue that we should address: a misunderstanding about the use case / purpose for these fielods.

**Comment by SR33G33** [comment]
Fixed it, now TermDescription has nothing to do with the TermRegex and the corresponding tests and checks have been modified/removed, will update the later PRs with this as well

**Review by pconrad — APPROVED** [review]
LGTM
